name: tfsec
on:
  pull_request:
    types: [opened, reopened]
env:
  TERRAFORM_VERSION: "1.0.6"

jobs:
  tfsec:
      name: runner /tfsec
      runs-on: ubuntu-latest

      steps:
        - name: Clone repo
          uses: actions/checkout@master
        - name: tfsec
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            soft_fail: true

  test-pr-check:
    name: tfsec (github-pr-check)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # The check is expected to fail on the test data
      - name: Check return codes
        if: success() || failure ()
        run: |
          tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
          if [[ "$tfsec_return" -eq 1 ]]; then
            echo "tfsec correctly returned failure ${tfsec_return}"
          else
            echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
            exit 1
          fi
          if [[ "$reviewdog_return" -eq 0 ]]; then
            echo "reviewdog correctly returned success: ${reviewdog_return}"
          else
            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
            exit 1
          fi
