name: tfsec
on:
  pull_request:
    types: [opened, reopened]
env:
  TERRAFORM_VERSION: "1.0.6"

jobs:
  tfsec:
      name: runner /tfsec
      runs-on: ubuntu-latest

      steps:
        - name: Clone repo
          uses: actions/checkout@master
        - name: tfsec
          id  : test
          uses: aquasecurity/tfsec-action@v1.0.0
          with:
            soft_fail: true
        - name: Check return codes
          if: success() || failure ()
          run: |
            tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
            if [[ "$tfsec_return" -eq 1 ]]; then
              echo "{tfsec_return}"
            else
              echo "${tfsec_return}"
              exit 1
            fi

